routes/web.php
    Route::get('inactive', 'Vacations\PleaController@getInactive')->name('plea.inactive');
    Route::resource('plea', 'Vacations\PleaController');
    Route::get('clock', 'ClockController@clock');
    Route::resource('clocklog', 'Vacations\ClockLogController');
    
    Route::get('getCalendarEvents/{id?}', 'Vacations\CalendarController@getCalendarEvents')->name('getCalendarEvents');
    Route::get('authMeWith/{user_email}', 'EmployeeController@authMeWith');
    Route::get('debugToolForBalanceCheck/{user_id?}/{date?}', 'EmployeeController@debugToolForBalanceCheck');
});

Route::group(['prefix' => 'super', 'as' => 'super.'], function () {
    Route::get('user/incidents', 'Vacations\IncidentController@index')->name('user.incidents.index');
    Route::get('user/incidents/{user}', 'Vacations\IncidentController@show')->name('user.incidents.show');
    Route::post('user/incidents/{user}', 'Vacations\IncidentController@store')->name('user.incidents.store');
    Route::get('user/incidents/{user}/review', 'Vacations\IncidentController@review')->name('user.incidents.review');
    Route::put('user/incidents/{user}', 'Vacations\IncidentController@update')->name('user.incidents.update');
    Route::get('approve/{request}', 'Vacations\SuperController@approve')->name('approve');
    Route::get('eventstable', 'Vacations\EventsController@table');
    Route::post('requests', 'Vacations\SuperController@requests')->name('requests');
    Route::post('delete_approved_request', 'Vacations\SuperController@deleteApprovedRequest');
    Route::post('incidents', 'Vacations\SuperController@incidents');
    Route::post('incidents/{id}', 'Vacations\SuperController@update');
    Route::resource('events', 'Vacations\EventsController');
    Route::get('clocklog/today', 'Vacations\ClockLogController@today')->name('clocklog.supervisor.today');
    Route::get('clocklog/review_problems', 'Vacations\ClockLogController@review_problems')->name('clocklog.supervisor.review_problems');
    Route::get('clocklog/missing_logs', 'Vacations\ClockLogController@missing_logs')->name('clocklog.supervisor.missing_logs');
    Route::post('clocklog/approve_clock_incidents', 'Vacations\ClockLogController@approve_clock_incidents')->name('clocklog.supervisor.approve_clock_incidents');
    Route::post('clocklog/create_abscent_incident', 'Vacations\ClockLogController@create_abscent_incident')->name('clocklog.supervisor.create_abscent_incident');
    Route::post('clocklog/manage_absents', 'Vacations\ClockLogController@manage_absents')->name('clocklog.supervisor.manage_absents');
    Route::get('clocklog', 'Vacations\ClockLogController@supervisor')->name('clocklog.supervisor');
    Route::get('clocklog/history', 'Vacations\ClockLogController@history')->name('clocklog.supervisor.history');
    // Route::get('userstable', 'UsersController@table');
    // Route::get('users/{id}/add', 'UsersController@addBenefit');
    // Route::post('users/{id}/add', 'UsersController@setBenefit');
    // Route::resource('users', 'UsersController');
    // Route::get('excel/requests', 'Export\ExcelController@requests');
    // Route::get('excel/incidents', 'Export\ExcelController@incidents');
    Route::get('view/incidents', 'Vacations\AdminController@incidents');
    Route::get('view/requests', 'Vacations\AdminController@requests')->name('view.requests');
    Route::get('view/schedule/{last_date?}/{direction?}', 'Vacations\AdminController@schedule')->name('view.schedule');
    Route::get('view/balances/{user_id?}', 'Vacations\AdminController@employee_balances')->name('view.employee_balances');
    Route::get('tableincidents', 'Vacations\AdminController@tableIncidents');
    Route::post('tableincidents', 'Vacations\AdminController@tableIncidents');
    Route::get('tablerequests', 'Vacations\AdminController@tableRequests');
    Route::post('tablerequests', 'Vacations\AdminController@tableRequests'); 
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('benefitjobs', 'Vacations\BenefitJobController');
    Route::get('clocklog/history', 'Vacations\AdminClocklogController@history')->name('clocklog.history');
    Route::get('incidents/history', 'Vacations\AdminController@history')->name('incidents.history');

    Route::get('balances', 'Vacations\AdminController@balances')->name('incidents.balances');
    Route::get('approve/{request}', 'Vacations\AdminController@approve')->name('approve');
    Route::get('view/balances/{user_id?}', 'Vacations\AdminController@admin_employee_balances')->name('view.employee_balances');
    /** Rutas para crear lineas de balances extraordinarias **/
    Route::get('balances/user', 'Vacations\BalanceUserController@index')->name('incidents.balances.create');
    Route::get('balances/user_year/{id}', 'Vacations\BalanceUserController@getYear');
    Route::post('balances/user', 'Vacations\BalanceUserController@store')->name('incidents.balances.store');
    /** Fin Rutas para crear lineas de balances extraordinarias **/

    // Route::resource('balances', 'AdminBalanceController');

    // Route::get('view/rules', 'AdminController@rules');
    // Route::get('masivetable', 'MasiveUsersController@table');

    // Route::get('config', 'AdminController@config');
    // Route::post('config', 'AdminController@setconfig');

    Route::get('export/{type}', 'Vacations\ExportController@index')->name('exports.index');
    Route::get('unprocessVacations/{date?}', 'Vacations\ExportController@unprocessVacations');
    Route::post('export_vacations', 'Vacations\ExportController@exportVacations')->name('exports.vacations');
    Route::post('export_incidents', 'Vacations\ExportController@exportIncidents')->name('exports.incidents');

    // Route::get('export', 'ExportController@export');
    // Route::get('getcsv', 'ExportController@getcsv');
    // Route::get('getxls', 'ExportController@getxls');

    // Route::get('users/{id}/add', 'UsersController@addBenefit');
    // Route::post('users/{id}/add', 'UsersController@setBenefit');
    // Route::get('users/{id}/login', 'UsersController@loginAs');

    // Route::post('masiveInfo', 'MasiveUsersController@userInfo');
    // Route::resource('masive', 'MasiveUsersController');
    Route::resource('incidents', 'Vacations\BenefitsController');
    Route::resource('schedule', 'ScheduleController');
    // Route::resource('generalist', 'GeneralistController');

    if(config('config.clockimport')) {
        Route::get('clock/import', 'ClockController@import');
        Route::post('clock/process', 'ClockController@manualprocess');
    }
});
 
//fin
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/*Route::get('/home', function(){
  return view('evaluacion-desempeno/que-es-evaluacion-desempeno');
})->middleware('auth');*/


/********************************************************************************** */
//rutas para codigos que nos ayuden a actualizar información y/o parchar ciertos errores
//inicio ***************
Route::get('turnRegionIntoForeign', 'Fixes\FixingCronDataController@turnRegionIntoForeign');
Route::get('crons','CronController@index');

//fin
//*************************************************************************

/*
Empieza evaluacion de desempeño
*/
//Route::group([ 'middleware' => 'admin'], function () {
    Route::get('lista-empleados', 'EvaluacionDesempeno\UsersController@lista_usuarios');
    Route::post('cambiar-jefe/{id_user}', 'EvaluacionDesempeno\UsersController@cambiar_jefe');
    Route::get('cambiar-jefe/{id_user}', 'EvaluacionDesempeno\UsersController@cambiar_jefe');
    Route::get('estadisticas', 'EvaluacionDesempeno\Admin\EstadisticasController@estadisticas');
    Route::post('estadisticas', 'EvaluacionDesempeno\Admin\EstadisticasController@estadisticas');
    Route::get('estadisticasAP', 'EvaluacionDesempeno\Admin\EstadisticasController@estadisticasConAreasYPuestos');
    Route::resource('areas', 'EvaluacionDesempeno\Admin\GruposAreasController');
    Route::resource('puestos', 'EvaluacionDesempeno\Admin\NivelesPuestosController');
    Route::resource('periodos', 'EvaluacionDesempeno\Admin\PeriodosController');
    Route::post('crear-periodo', 'EvaluacionDesempeno\Admin\PeriodosController@create');
    Route::post('editar-periodo', 'EvaluacionDesempeno\Admin\PeriodosController@edit');
    Route::get('borrar-periodo/{id}', 'EvaluacionDesempeno\Admin\PeriodosController@destroy');
    Route::post('borrar-periodo', 'EvaluacionDesempeno\Admin\PeriodosController@destroy');
    Route::resource('tipos-factores', 'EvaluacionDesempeno\Admin\TiposFactoresController');
    Route::post('crear-tipo-factor', 'EvaluacionDesempeno\Admin\TiposFactoresController@create');
    Route::post('editar-tipo-factor', 'EvaluacionDesempeno\Admin\TiposFactoresController@edit');
    Route::get('borrar-tipo-factor/{id}', 'EvaluacionDesempeno\Admin\TiposFactoresController@destroy');
    Route::post('borrar-tipo-factor', 'EvaluacionDesempeno\Admin\TiposFactoresController@destroy');
    Route::resource('etiquetas', 'EvaluacionDesempeno\Admin\EtiquetasController');
    Route::post('crear-etiqueta', 'EvaluacionDesempeno\Admin\EtiquetasController@create');
    Route::post('editar-etiqueta', 'EvaluacionDesempeno\Admin\EtiquetasController@edit');
    Route::get('borrar-etiqueta/{id}', 'EvaluacionDesempeno\Admin\EtiquetasController@destroy');
    Route::post('borrar-etiqueta', 'EvaluacionDesempeno\Admin\EtiquetasController@destroy');
    Route::resource('factores', 'EvaluacionDesempeno\Admin\FactoresController');
    Route::resource('familias-factores', 'EvaluacionDesempeno\Admin\FamiliasFactoresController');
    Route::post('editar-familia-factores', 'EvaluacionDesempeno\Admin\FamiliasFactoresController@edit');
  Route::get('tipos-evaluacion', 'EvaluacionDesempeno\Admin\MatrizEvaluacionController@tipos_evaluacion');
  Route::post('editar-tipo-evaluacion', 'EvaluacionDesempeno\Admin\MatrizEvaluacionController@edit_tipo_evaluacion');

app/Models/Schedule.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    /**
     * Fields that can be mass assigned.
     *
     * @var array
     */
    protected $fillable = ['shift','in','out'];

    public function workshiftsFixed()
    {
        return $this->hasMany(WorkshiftFixed::class);
    }

    public function getTimeOfWork(){
        $start = new Carbon($this->in);
        $end = new Carbon($this->out);
        return $start->diffInMinutes($end, false);
    }
}

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Employee;

use App\Models\Region;
use App\Models\Schedule;
use App\Models\Workshift;
use Illuminate\Http\Request;
use App\Models\WorkshiftFixed;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ScheduleRequest;

class ScheduleController extends Controller
{
    protected $daysOfWeek;

    public function __construct(){
        $this->middleware('permission:admin');
        $this->daysOfWeek = [
            'Mon' => 'Lunes',
            'Tue' => 'Martes',
            'Wed' => 'Miercoles',
            'Thu' => 'Jueves',
            'Fri' => 'Viernes',
            'Sat' => 'Sabado',
            'Sun' => 'Domingo',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $regions = Region::where('workshift','5x2')->get();
        return view('vacations.admin.schedule.index', compact('regions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $days = $this->daysOfWeek;
        $schedules = Schedule::all();
        return view('vacations.admin.schedule.create', compact('days', 'schedules'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ScheduleRequest $request)
    {
        $request = $request->validated();
        try {
            DB::beginTransaction();
            $region = Region::create([
                'name' => $request['name'],
                'rules' => null,
                'workshift' => $request['workshift'],
            ]);

            foreach($this->daysOfWeek as $key => $day){
                WorkshiftFixed::create([
                    'day' => $key,
                    'labor' => isset($request['labor'][$key]),
                    'region_id' => $region->id,
                    'schedule_id' => isset($request['schedule'][$key])?$request['schedule'][$key]:null,
                ]);
            }
            DB::commit();
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->route('admin.schedule.create')->withErrors(['errors' => $th->getMessage()]);
        }
        flash('Los cambios se guardaron satisfactoriamente.','success');
        return redirect()->route('admin.schedule.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $region = Region::where('id',$id)->firstOrFail();
        $currMonth = date('m');
        $totalDays = date('t');
        $date = mktime(0,0,0, $currMonth, 1, date('y'));
        $dayNumber = date('N', $date);
        // dd($currMonth, $totalDays, $dayNumber, $date);
        if($region->workshift == '5x2'){
            return view('admin.schedule.show5x2', compact('region', 'currMonth', 'totalDays', 'dayNumber'));
        }else{
            return view('admin.schedule.show6x2', compact('region'));
        }

        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $region = Region::with('workshiftFixed.schedule')->findOrFail($id);
        $region->loadWeekSchedule();
        $days = $this->daysOfWeek;
        $schedules = Schedule::all();
        return view('vacations.admin.schedule.edit', compact('region', 'days', 'schedules'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ScheduleRequest $request, $id)
    {
        $region = Region::findOrFail($id);
        $request = $request->validated();
        try {
            DB::beginTransaction();
            
            $newRegion = Region::create([
                'name' => $request['name'],
                'rules' => null,
                'workshift' => $request['workshift'],
            ]);

            foreach($this->daysOfWeek as $key => $day){
                WorkshiftFixed::create([
                    'day' => $key,
                    'labor' => isset($request['labor'][$key]),
                    'region_id' => $newRegion->id,
                    'schedule_id' => isset($request['schedule'][$key])?$request['schedule'][$key]:null,
                ]);
            }

            Employee::where('region_id', $region->id)
            ->update(['region_id' => $newRegion->id]);

            $region->delete();

            DB::commit();
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->route('admin.schedule.edit', $id)->withErrors(['errors' => $th->getMessage()]);
        }
        flash('Los cambios se guardaron satisfactoriamente.','success');
        return redirect()->route('admin.schedule.edit', $newRegion->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::where('region_id',$id)->first();
        if($user) {
            flash('Para borrar la región debe mover a la gente que pertenece a este horario a otro distinto.','warning');
            return redirect('admin/schedule');
        }
        flash('La región fue borrada correctamente','success');
        $region = Region::where('id',$id)->first();
        $region->delete();
        return redirect('admin/schedule');
    }

}

resources/views/vacations/admin/schedule/create.blade.php
@extends('vacations.app')

@section('content')

<div class="row mb-3">
    <div class="col-12 blue_header rounded py-3">
        <h2 class="font-italic font-weight-bold m-0"><i class="far fa-calendar-alt"></i> Horarios</h2>
    </div>
</div>

<div class="row mb-2">
    <div class="col-12 py-3">
        <h3 class="text-blue font-italic font-weight-bold m-0" style="border-bottom: 4px solid #898788">Crear Horario</h3>
    </div>
</div>

<form action="{{ route('admin.schedule.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="name">Nombre</label>
                <input type="text" name="name" value="{{ old('name') }}" class="form-control" required>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="workshift">Jornada Laboral</label>
                <select name="workshift" class="form-control" required>
                    <option value="5x2" {{ old('workshift') }}>Semana de 7 días</option>
                </select>
            </div>
        </div>
    </div>
    <hr>
    @foreach ($days as $key => $day)
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="day" class="w-25 d-inline mx-2">Día</label>
                    <input type="text" class="form-control w-75 d-inline" value="{{ $day }}" disabled>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <div class="custom-control custom-checkbox ">
                        <input type="checkbox" name="labor[{{ $key }}]" value="1" class="custom-control-input cbox-labor" id="cbox_labor[{{ $key }}]" {{ in_old_input(session()->getOldInput(), 'labor', '', $key)?'checked':''}}>
                        <label class="custom-control-label" for="cbox_labor[{{ $key }}]">Laboral</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <label for="schedule" class="w-25 d-inline mx-2">Horario</label>
                <select name="schedule[{{ $key }}]" class="form-control w-75 d-inline select-schedule" {{ in_old_input(session()->getOldInput(), 'schedule', '', $key)?:'disabled' }}>
                    <option value="">Eliga un horario</option>
                    @foreach ($schedules as $schedule)
                        <option value="{{ $schedule->id }}" {{ in_old_input(session()->getOldInput(), 'schedule', '', $key, in_old_input(session()->getOldInput(), 'schedule', '', $key)) == $schedule->id?'selected':'' }}>
                            {{ $schedule->shift }}  /  {{ $schedule->in }} - {{ $schedule->out }}
                        </option>
                    @endforeach
                </select>
            </div>
        </div>
    @endforeach
    <div class="text-right">
        <input type="submit" value="Guardar" class="btn btn-primary">
        <a href="{{ route('admin.schedule.index') }}" class="btn btn-info">Regresar</a>
    </div>
</form>

@endsection

@section('scripts')
<script>
    $(function(){
        $('.cbox-labor').on('change', function(){
            const isChecked = $(this).is(":checked");
            const row = $(this).closest('.row');
            const select = row.find('.select-schedule');
            if(!isChecked){
                select.prop('selectedIndex', 0);
            }
            select.attr('required', isChecked).attr('disabled', !isChecked);
        });
    });
</script>
@endsection

resources/views/vacations/admin/schedule/edit.blade.php
@extends('vacations.app')

@section('content')

<div class="row mb-3">
    <div class="col-12 blue_header rounded py-3">
        <h2 class="font-italic font-weight-bold m-0"><i class="far fa-calendar-alt"></i> Horarios</h2>
    </div>
</div>

<div class="row mb-2">
    <div class="col-12 py-3">
        <h3 class="text-blue font-italic font-weight-bold m-0" style="border-bottom: 4px solid #898788">Crear Horario</h3>
    </div>
</div>

<form action="{{ route('admin.schedule.update', $region->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="name">Nombre</label>
                <input type="text" name="name" value="{{ old('name', $region->name) }}" class="form-control" required>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="workshift">Jornada Laboral</label>
                <select name="workshift" class="form-control" required>
                    <option value="5x2" {{ old('workshift', $region->workshift) === '5x2'?'selected':'' }}>Semana de 7 días</option>
                </select>
            </div>
        </div>
    </div>
    <hr>
    @foreach ($days as $key => $day)
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="day" class="w-25 d-inline mx-2">Día</label>
                    <input type="text" class="form-control w-75 d-inline" value="{{ $day }}" disabled>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <div class="custom-control custom-checkbox ">
                        <input type="checkbox" name="labor[{{ $key }}]" value="1" class="custom-control-input cbox-labor" id="cbox_labor[{{ $key }}]" {{ in_old_input(session()->getOldInput(), 'labor', $region->getScheduleIdByDay($key), $key)?'checked':'' }}>
                        <label class="custom-control-label" for="cbox_labor[{{ $key }}]">Laboral</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <label for="schedule" class="w-25 d-inline mx-2">Horario</label>
                <select name="schedule[{{ $key }}]" class="form-control w-75 d-inline select-schedule" {{ in_old_input(session()->getOldInput(), 'schedule', $region->getScheduleIdByDay($key), $key)?:'disabled' }}>
                    <option value="">Eliga un horario</option>
                    @foreach ($schedules as $schedule)
                        <option value="{{ $schedule->id }}" {{ in_old_input(session()->getOldInput(), 'schedule', $region->getScheduleIdByDay($key), $key, in_old_input(session()->getOldInput(), 'schedule', $region->getScheduleIdByDay($key), $key)) == $schedule->id?'selected':'' }}>
                            {{ $schedule->shift }}  /  {{ $schedule->in }} - {{ $schedule->out }}
                        </option>
                    @endforeach
                </select>
            </div>
        </div>
    @endforeach
    <div class="text-right">
        <input type="submit" value="Guardar" class="btn btn-primary">
        <a href="{{ route('admin.schedule.index') }}" class="btn btn-info">Regresar</a>
    </div>
</form>

@endsection

@section('scripts')
<script>
    $(function(){
        $('.cbox-labor').on('change', function(){
            const isChecked = $(this).is(":checked");
            const row = $(this).closest('.row');
            const select = row.find('.select-schedule');
            if(!isChecked){
                select.prop('selectedIndex', 0);
            }
            select.attr('required', isChecked).attr('disabled', !isChecked);
        });
    });
</script>
@endsection

resources/views/vacations/admin/schedule/index.blade.php
@extends('vacations.app')

@section('content')

<div class="row mb-3">
    <div class="col-12 blue_header rounded py-3">
        <h2 class="font-italic font-weight-bold m-0"><i class="far fa-calendar-alt"></i> Horarios</h2>
    </div>
</div>

<div class="row mb-2">
    <div class="col-12 py-3">
        <h3 class="text-blue font-italic font-weight-bold m-0" style="border-bottom: 4px solid #898788">Administrar Horarios</h3>
    </div>
</div>

<div class="text-right">
    <a href="{{ url('admin/schedule/create') }}" class="btn btn-primary">Crear Horario</a>
</div>

<div>
    <div class="form-group">
        <label>Horario</label>
        <select id="select_schedule" class="form-control" data-live-search="true">
            <option value="" selected disabled>...Seleccione un horario</option>
            @foreach ($regions as $region)
                <option value="{{ $region->id }}">{{ $region->name }}</option>
            @endforeach
        </select>
    </div>
</div>

<div class="card card-3 mt-4">
    <div class="card-body">
        <div class="tab-content" id="pills-tabContent">
            @foreach($regions as $region)                
                <div class="tab-pane fade" id="pills-{{ $region->id }}" role="tabpanel" aria-labelledby="pills-{{ $region->id }}-tab">
                    <div class="row justify-content-center mb-4">
                        <div class="col-md-4">
                            <a href="{{ url('admin/schedule/' . $region->id . '/edit') }}" class="btn btn-primary btn-block">Editar</a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="blue_header">
                            <tr>
                                <th>Día</th>
                                <th>Entrada</th>
                                <th>Salida</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($region->workshiftFixed as $day)
                                    <tr class="{{ $day->labor?'':'table-secondary' }}">
                                        <td>{{ __('bd.l-'.$day->day) }}</td>
                                        <td>{{ $day->getInTime() }}</td>
                                        <td>{{ $day->getOutTime() }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="pull-right">
                        <a title="Ver" alt="Ver" href="{{App::make('url')->to('/')}}/admin/schedule/{{$region->id}}">
                            <span class="glyphicon glyphicon-eye-open"></span>
                        </a> &nbsp;&nbsp;
                        <a title="Editar" alt="Editar" href="{{App::make('url')->to('/')}}/admin/schedule/{{$region->id}}/edit">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
    $('#select_schedule').selectpicker();

    $(function(){
        $('#select_schedule').on('change', function(){
            const id = $('#select_schedule').selectpicker().val();
            $('.tab-pane').removeClass('show active');
            $('#pills-' + id).addClass('show active')
        });
    });
</script>    
@endsection

resources/views/vacations/admin/schedule/show6x2.blade.php
@extends('layouts.app')

@section('content')


@endsection